const couponItems = [
  {
    code: 'WELCOME20',
    name: 'Welcome Offer - 20% OFF',
    description: 'Flat 20% off on your first order',
    type: 'Percentage',
    discount: '20% OFF',
    minOrder: 199,
    usageLimit: 500,
    usageCount: 125,
    validityStart: new Date('2025-05-10'),
    validityEnd: new Date('2027-12-31'),
    status: 'Active',
    isNew: true,
    priority: true,
    applicableSize: 'All Sizes',
    image: '/images/Coupons/welcome_offer.png'
  },
  {
    code: 'PIZZA50',
    name: 'Flat ₹50 OFF',
    description: 'Flat ₹50 off on orders above ₹299',
    type: 'Fixed',
    discount: '₹50 OFF',
    minOrder: 299,
    usageLimit: 1000,
    usageCount: 230,
    validityStart: new Date('2025-05-01'),
    validityEnd: new Date('2027-12-31'),
    status: 'Active',
    isNew: false,
    priority: true,
    applicableSize: 'Medium',
    image: '/images/Coupons/Cheese_lover.png'
  },
  {
    code: 'MEGA100',
    name: 'Mega Discount',
    description: 'Flat ₹100 off on orders above ₹699',
    type: 'Fixed',
    discount: '₹100 OFF',
    minOrder: 699,
    usageLimit: 500,
    usageCount: 75,
    validityStart: new Date('2025-05-05'),
    validityEnd: new Date('2027-12-31'),
    status: 'Active',
    isNew: false,
    priority: false,
    applicableSize: 'Large',
    image: '/images/Coupons/Combo_offer.png'
  },
  {
    code: 'FREESHIP',
    name: 'Free Delivery',
    description: 'Free delivery on all orders',
    type: 'Free Shipping',
    discount: 'Free Delivery',
    minOrder: 0,
    usageLimit: 9999,
    usageCount: 320,
    validityStart: new Date('2025-05-01'),
    validityEnd: new Date('2027-12-31'),
    status: 'Active',
    isNew: false,
    priority: false,
    applicableSize: 'All Sizes',
    image: '/images/Coupons/Free_delivery .png' // Keep the space!
  },
  {
    code: 'WEEKEND30',
    name: 'Weekend Special',
    description: '30% off on all weekend orders',
    type: 'Percentage',
    discount: '30% OFF',
    minOrder: 249,
    usageLimit: 300,
    usageCount: 90,
    validityStart: new Date('2025-05-01'),
    validityEnd: new Date('2027-12-31'),
    status: 'Inactive',
    isNew: false,
    priority: false,
    applicableSize: 'Medium',
    image: '/images/Coupons/Weekend_sale.png'
  }
];

module.exports = couponItems;
