const ingredientItems = [
  // CRUST OPTIONS
  {
    name: "Classic Hand Tossed",
    category: "crust",
    image: "/images/Crust/Classic_Hand_Tossed.jpg",
    extraPrice: 0,
    isVeg: true,
    displayOrder: 1,
  },
  {
    name: "Pan Pizza",
    category: "crust",
    image: "/images/Crust/Pan_Pizza.jpg",
    extraPrice: 40,
    isVeg: true,
    displayOrder: 2,
  },
  {
    name: "Stuffed Crust",
    category: "crust",
    image: "/images/Crust/Stuffed_Crust.jpg",
    extraPrice: 60,
    isVeg: true,
    displayOrder: 3,
  },
  {
    name: "Wheat Thin Crust",
    category: "crust",
    image: "/images/Crust/Wheat_Thin_Crust.jpg",
    extraPrice: 30,
    isVeg: true,
    displayOrder: 4,
  },
  {
    name: "Cheese Burst",
    category: "crust",
    image: "/images/Crust/chesse_Burst.jpg",
    extraPrice: 80,
    isVeg: true,
    isPopular: true,
    displayOrder: 5,
  },

  // SAUCE OPTIONS
  {
    name: "Tomato Basil",
    category: "sauce",
    image: "/images/Sauce/Tomato_Basil.jpg",
    extraPrice: 0,
    isVeg: true,
    displayOrder: 1,
  },
  {
    name: "Alfredo Sauce",
    category: "sauce",
    image: "/images/Sauce/Alfredo_Sauce.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 2,
  },
  {
    name: "BBQ Sauce",
    category: "sauce",
    image: "/images/Sauce/BBQ_Sauce.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 3,
  },
  {
    name: "Pesto Sauce",
    category: "sauce",
    image: "/images/Sauce/Pesto_Sauce.jpg",
    extraPrice: 25,
    isVeg: true,
    displayOrder: 4,
  },
  {
    name: "Spicy Arrabbiata",
    category: "sauce",
    image: "/images/Sauce/Spicy_Arrabbiata.jpg",
    extraPrice: 15,
    isVeg: true,
    displayOrder: 5,
  },

  // CHEESE OPTIONS
  {
    name: "Mozzarella",
    category: "cheese",
    image: "/images/Cheese/Mozzarella.jpg",
    extraPrice: 0,
    isVeg: true,
    displayOrder: 1,
  },
  {
    name: "Cheddar",
    category: "cheese",
    image: "/images/Cheese/Cheddar.jpg",
    extraPrice: 30,
    isVeg: true,
    displayOrder: 2,
  },
  {
    name: "Parmesan",
    category: "cheese",
    image: "/images/Cheese/parmesan_cheese_1.jpg",
    extraPrice: 40,
    isVeg: true,
    displayOrder: 3,
  },
  {
    name: "Extra Cheese",
    category: "cheese",
    image: "/images/Cheese/extra_cheese.jpg",
    extraPrice: 50,
    isVeg: true,
    isPopular: true,
    displayOrder: 4,
  },
  {
    name: "Vegan Cheese",
    category: "cheese",
    image: "/images/Cheese/Vegan.jpg",
    extraPrice: 45,
    isVeg: true,
    displayOrder: 5,
  },

  // VEG TOPPINGS
  {
    name: "Paneer Cubes",
    category: "veg-topping",
    image: "/images/Veg Toppings/Paneer_Cubes.jpg",
    extraPrice: 40,
    isVeg: true,
    isPopular: true,
    displayOrder: 1,
  },
  {
    name: "Capsicum",
    category: "veg-topping",
    image: "/images/Veg Toppings/Capsicum.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 2,
  },
  {
    name: "Onion",
    category: "veg-topping",
    image: "/images/Veg Toppings/Onion.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 3,
  },
  {
    name: "Mushroom",
    category: "veg-topping",
    image: "/images/Veg Toppings/Mushroom.jpg",
    extraPrice: 30,
    isVeg: true,
    displayOrder: 4,
  },
  {
    name: "Sweet Corn",
    category: "veg-topping",
    image: "/images/Veg Toppings/Sweet_Corn.jpg",
    extraPrice: 25,
    isVeg: true,
    displayOrder: 5,
  },
  {
    name: "Jalapeno",
    category: "veg-topping",
    image: "/images/Veg Toppings/Jalapeno.jpg",
    extraPrice: 25,
    isVeg: true,
    displayOrder: 6,
  },
  {
    name: "Black Olive",
    category: "veg-topping",
    image: "/images/Veg Toppings/Black_Olive.jpg",
    extraPrice: 30,
    isVeg: true,
    displayOrder: 7,
  },
  {
    name: "Tomato",
    category: "veg-topping",
    image: "/images/Veg Toppings/Tomato.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 8,
  },
  {
    name: "Spinach",
    category: "veg-topping",
    image: "/images/Veg Toppings/Spinach.jpg",
    extraPrice: 20,
    isVeg: true,
    displayOrder: 9,
  },

  // MEAT TOPPINGS
  {
    name: "Pepper Barbecue Chicken Chunks",
    category: "meat-topping",
    image: "/images/Signature_Non-Veg_Pizzas/Pepper_Barbecue_Chicken.jpg",
    extraPrice: 60,
    isVeg: false,
    isPopular: true,
    displayOrder: 1,
  },
  {
    name: "Chicken Sausage Slices",
    category: "meat-topping",
    image: "/images/Garlic_Breads_and_Sides/Chicken_Nuggets.jpg",
    extraPrice: 50,
    isVeg: false,
    displayOrder: 2,
  },
  {
    name: "Grilled Chicken Strips",
    category: "meat-topping",
    image: "/images/Garlic_Breads_and_Sides/Chicken_Wings.jpg",
    extraPrice: 55,
    isVeg: false,
    displayOrder: 3,
  },
  {
    name: "Chicken Pepperoni",
    category: "meat-topping",
    image: "/images/Signature_Non-Veg_Pizzas/Chicken_Pepperoni_Feast.jpg",
    extraPrice: 70,
    isVeg: false,
    isPopular: true,
    displayOrder: 4,
  },
];

module.exports = ingredientItems;
